package com.example.a5120_shademate.data.api

import com.example.a5120_shademate.BuildConfig
import android.content.Context
import com.example.a5120_shademate.R
import com.mapbox.geojson.Point
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import kotlin.math.abs
import kotlin.math.asin
import kotlin.math.cos
import kotlin.math.pow
import kotlin.math.sin
import kotlin.math.sqrt

class WalkingRouteRepository(context: Context) {
    private val accessToken = context.getString(R.string.mapbox_access_token)
    private val weatherApiKey = BuildConfig.OPENWEATHER_API_KEY

    private val retrofit = Retrofit.Builder()
        .baseUrl("https://api.mapbox.com/")
        .addConverterFactory(GsonConverterFactory.create())
        .build()

    private val service = retrofit.create(MapboxDirectionsService::class.java)
    private val weatherService =
        WeatherApiClient.retrofit.create(WeatherApiService::class.java)
    private val heatMapService =
        AppApiClient.retrofit.create(HeatMapApiService::class.java)

    suspend fun getWalkingRouteOptions(
        origin: Point,
        destination: Point,
    ): List<WalkingRouteGeometry> {
        val response = service.getWalkingRoutes(
            coordinates = buildMapboxCoordinates(origin, destination),
            alternatives = true,
            accessToken = accessToken,
        )

        var mapboxRoutes = response.routes
            .mapNotNull { it.toWalkingRouteGeometry() }
            .distinctByRouteShape()

        if (mapboxRoutes.size < 2) {
            // Mapbox sometimes returns only one alternative for short/simple walking trips.
            // Keep the cool route unchanged, then ask Mapbox for a small via-point route so
            // the regular route is still generated by Mapbox and visibly different for demos.
            mapboxRoutes = (mapboxRoutes + getRegularRouteDetourOptions(origin, destination))
                .distinctByRouteShape()
        }

        return mapboxRoutes.take(2)
    }

    suspend fun getRecommendedWalkingRoute(
        origin: Point,
        destination: Point,
    ): WalkingRouteGeometry? {
        val response = service.getWalkingRoutes(
            coordinates = buildMapboxCoordinates(origin, destination),
            alternatives = false,
            accessToken = accessToken,
        )

        return response.routes.firstOrNull()?.toWalkingRouteGeometry()
    }

    suspend fun getRouteWeatherSummary(point: Point): RouteWeatherSummary {
        val weatherResponse = weatherService.getOneCallWeather(
            lat = point.latitude(),
            lon = point.longitude(),
            apiKey = weatherApiKey,
        )

        val calendar = java.util.Calendar.getInstance()
        val month = calendar.get(java.util.Calendar.MONTH) + 1
        val hour = calendar.get(java.util.Calendar.HOUR_OF_DAY)

        val heatMapData = try {
            heatMapService.getHeatMapAverage(
                HeatMapAverageRequest(
                    lat = point.latitude(),
                    lon = point.longitude(),
                    currentMonth = month,
                    currentHour = hour
                )
            )
        } catch (e: Exception) {
            null
        }

        val sunRatio = heatMapData?.sunExposureRatio
        val shadeScore = sunRatio?.let { ((1.0 - it) * 100).toInt() }

        val feelsLike = weatherResponse.current.feelsLike?.toInt()
        val heatScore = calculateHeatExposureScore(feelsLike, sunRatio)

        return RouteWeatherSummary(
            feelsLikeCelsius = feelsLike,
            uvLevel = weatherResponse.current.uvi?.toInt(),
            shadeCoverageScore = shadeScore,
            heatExposureScore = heatScore,
            sunExposureRatio = sunRatio,
        )
    }

    private fun calculateHeatExposureScore(feelsLikeTemp: Int?, sunRatio: Double?): Int? {
        if (feelsLikeTemp == null || sunRatio == null) return null
        val tempMin = 15.0
        val tempMax = 40.0
        val tempFactor = ((feelsLikeTemp - tempMin) / (tempMax - tempMin)).coerceIn(0.0, 1.0)
        val combinedScore = (tempFactor * 70.0) + (sunRatio * 30.0)
        return combinedScore.toInt().coerceIn(0, 100)
    }

    private suspend fun getRegularRouteDetourOptions(
        origin: Point,
        destination: Point,
    ): List<WalkingRouteGeometry> {
        return buildRegularRouteViaPoints(origin, destination).mapNotNull { viaPoint ->
            runCatching {
                val response = service.getWalkingRoutes(
                    coordinates = buildMapboxCoordinates(origin, viaPoint, destination),
                    alternatives = false,
                    accessToken = accessToken,
                )
                response.routes.firstOrNull()?.toWalkingRouteGeometry()
            }.getOrNull()
        }
    }

    private fun buildRegularRouteViaPoints(origin: Point, destination: Point): List<Point> {
        val directDistanceMeters = routeDistanceMeters(origin, destination)
        if (directDistanceMeters < 80.0) return emptyList()

        val midpointLatitude = (origin.latitude() + destination.latitude()) / 2.0
        val midpointLongitude = (origin.longitude() + destination.longitude()) / 2.0
        val referenceLatitude = Math.toRadians(midpointLatitude)
        val metersPerDegreeLongitude = (METERS_PER_DEGREE_LATITUDE * cos(referenceLatitude))
            .coerceAtLeast(1.0)

        val dx = (destination.longitude() - origin.longitude()) * metersPerDegreeLongitude
        val dy = (destination.latitude() - origin.latitude()) * METERS_PER_DEGREE_LATITUDE
        val segmentLength = sqrt(dx * dx + dy * dy)
        if (segmentLength == 0.0) return emptyList()

        val offsetMeters = (directDistanceMeters * 0.18).coerceIn(120.0, 650.0)
        val perpendicularX = -dy / segmentLength
        val perpendicularY = dx / segmentLength

        return listOf(1.0, -1.0).map { side ->
            Point.fromLngLat(
                midpointLongitude + (side * perpendicularX * offsetMeters / metersPerDegreeLongitude),
                midpointLatitude + (side * perpendicularY * offsetMeters / METERS_PER_DEGREE_LATITUDE),
            )
        }
    }

    private fun buildMapboxCoordinates(vararg points: Point): String {
        return points.joinToString(";") { point ->
            "${point.longitude()},${point.latitude()}"
        }
    }

    private fun DirectionsRoute.toWalkingRouteGeometry(): WalkingRouteGeometry? {
        val points = geometry.coordinates.mapNotNull { coordinate ->
            if (coordinate.size >= 2) {
                Point.fromLngLat(coordinate[0], coordinate[1])
            } else {
                null
            }
        }
        if (points.size < 2) return null

        return WalkingRouteGeometry(
            points = points,
            distanceMeters = distance,
            durationSeconds = duration,
        )
    }

    private fun List<WalkingRouteGeometry>.distinctByRouteShape(): List<WalkingRouteGeometry> {
        val distinctRoutes = mutableListOf<WalkingRouteGeometry>()
        forEach { route ->
            if (distinctRoutes.none { existingRoute -> existingRoute.hasSameRouteShape(route) }) {
                distinctRoutes += route
            }
        }
        return distinctRoutes
    }

    private fun WalkingRouteGeometry.hasSameRouteShape(other: WalkingRouteGeometry): Boolean {
        val similarDistance = abs(distanceMeters - other.distanceMeters) < 15.0
        val similarDuration = abs(durationSeconds - other.durationSeconds) < 20.0
        val samplePointsClose = routeSamplePoints().zip(other.routeSamplePoints())
            .all { (first, second) -> routeDistanceMeters(first, second) < 20.0 }
        return similarDistance && similarDuration && samplePointsClose
    }

    private fun WalkingRouteGeometry.routeSamplePoints(): List<Point> {
        if (points.isEmpty()) return emptyList()
        val lastIndex = points.lastIndex
        return listOf(
            0,
            lastIndex / 3,
            lastIndex / 2,
            (lastIndex * 2) / 3,
            lastIndex,
        ).distinct().map { index -> points[index] }
    }

    private fun routeDistanceMeters(start: Point, end: Point): Double {
        val earthRadiusMeters = 6_371_000.0
        val dLat = Math.toRadians(end.latitude() - start.latitude())
        val dLng = Math.toRadians(end.longitude() - start.longitude())
        val startLat = Math.toRadians(start.latitude())
        val endLat = Math.toRadians(end.latitude())

        val a = sin(dLat / 2).pow(2) + sin(dLng / 2).pow(2) * cos(startLat) * cos(endLat)
        val c = 2 * asin(sqrt(a))
        return earthRadiusMeters * c
    }

    private companion object {
        const val METERS_PER_DEGREE_LATITUDE = 111_320.0
    }
}

data class WalkingRouteGeometry(
    val points: List<Point>,
    val distanceMeters: Double,
    val durationSeconds: Double,
)

data class RouteWeatherSummary(
    val feelsLikeCelsius: Int?,
    val uvLevel: Int?,
    val shadeCoverageScore: Int? = null,
    val heatExposureScore: Int? = null,
    val sunExposureRatio: Double? = null,
)
